### PR TITLE
revising xquery 2

### PR DESCRIPTION
**Pull request by amberpeddicord**

### CODE REVIEW

**Comment by ebeshero** [comment]
@amberpeddicord I  know you're just getting started with this, so just ping me here when you're ready for me to review and potentially merge this over to the master branch.

**Comment by amberpeddicord** [comment]
@ebeshero Did you want me to change the part about lower-case and upper-case in XQuery 2 (since it doesn't help us narrow the results) and change it to have them tokenize on the string before commas in the distinct values of types?

**Comment by ebeshero** [comment]
@amberpeddicord Yes indeed. I was thinking we might mention how lower-case() of upper-case() might affect distinct values too, as a side note and something people can test. I can always munge the XML data a little to demonstrate how those functions can be useful!

**Comment by amberpeddicord** [comment]
@ebeshero Sounds good! I'll put the note in now.

**Comment by amberpeddicord** [comment]
@ebeshero I pushed the changes to this branch! Is there anything else that you want me to change?

**Comment by ebeshero** [comment]
This looks great, @amberpeddicord ! I am happy to approve your super helpful pull request!

**Comment by ebeshero** [comment]
@amberpeddicord I just merged it and I am deleting the branch from this remote repo. You should switch back to your master branch of this repo on your computer, and the delete your local branch. You can do that with `git branch -d AmberPokemon`.

**Comment by amberpeddicord** [comment]
@ebeshero I'm getting an error message that says `error: Cannot delete branch 'AmberPokemon' checked out at '/Users/amberpeddicord/Documents/GitHub/DHClass-Hub'` when I try.

**Comment by amberpeddicord** [comment]
@ebeshero Oops! Nevermind. I hadn't switched to the master when I tried the first time. The branch is deleted now.

**Pull request merged**
